# Generated by Django 4.0 on 2022-02-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default-user.svg', upload_to='', verbose_name='profile pic'),
        ),
    ]
